In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Các thông tin cần thiết: post_text, post_id, số lượt reactions, số lượt comments, số lượt shares, tổng số lượt tương tác và thời gian đăng bài

In [25]:
folder_path = 'Data/NintendoSwitch.npy'
post_list = np.load(folder_path, allow_pickle= True)
post_df_full = pd.read_csv('Data/NintendoSwitch.csv')

In [26]:
post_df_full1=post_df_full
post_df_full1['reactions'] = post_df_full1['reactions'].apply(lambda x : dict(eval(x)) )
post_df_full_reactions = post_df_full1['reactions'].apply(pd.Series )
post_df_full_with_reactions = pd.concat([post_df_full1, post_df_full_reactions], axis=1).drop('reactions', axis=1)
post_df_full_with_reactions[['post_text','post_id','like','love','haha','wow','sad','angry','care',
                                 'shares','comments','reaction_count', 'time']]

,post_text,post_id,like,love,haha,wow,sad,angry,care,shares,comments,reaction_count,time
0,You can now redeem your My Nintendo Platinum P...,661994359446422,311.0,122.0,3.0,10.0,NaN,NaN,9.0,64,24,455,2023-11-28 08:30:00
1,The Tetris 99 38th MAXIMUS CUP event will run ...,661989386113586,62.0,11.0,NaN,NaN,NaN,NaN,1.0,17,5,74,2023-11-28 08:15:00
2,The Tetris 99 37th MAXIMUS CUP event will run ...,661985226114002,42.0,11.0,NaN,NaN,NaN,1.0,NaN,16,3,54,2023-11-28 08:01:10
3,Groups ranging in size from 2 to 100 people ca...,660425176270007,144.0,21.0,4.0,3.0,NaN,1.0,4.0,18,28,177,2023-11-25 03:00:38
4,When’s the last time you visited Paldea? There...,660388266273698,316.0,96.0,27.0,3.0,1.0,2.0,6.0,28,60,451,2023-11-25 01:00:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,"Mario, Mallow, and… Bowser? Join this team of ...",647189700926888,1865.0,755.0,3.0,18.0,NaN,NaN,35.0,177,217,2676,2023-10-31 01:00:00
89,The first F-ZERO game has returned as a 99-pla...,647166684262523,356.0,90.0,NaN,5.0,NaN,2.0,5.0,38,21,458,2023-10-31 00:00:23
90,Expect the unexpected in Super Mario Bros. Won...,645738844405307,519.0,151.0,NaN,2.0,1.0,NaN,9.0,53,59,682,2023-10-28 06:00:18
91,To celebrate the two-year anniversary of the P...,645647254414466,176.0,35.0,2.0,4.0,NaN,NaN,1.0,16,5,218,2023-10-28 02:00:01
92,Splatoween is almost here! Will you shuffle wi...,645482841097574,494.0,273.0,2.0,5.0,NaN,NaN,10.0,126,28,784,2023-10-27 20:00:03

Làm sạch dữ liệu của các cột bằng việc chuyển các giá trị NaN sang giá trị 0

In [27]:
for i in range(0, len(post_df_full_with_reactions['like'].values), 1):
    if pd.isna(post_df_full_with_reactions['like'].values[i]):
        post_df_full_with_reactions['like'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['love'].values[i]):
        post_df_full_with_reactions['love'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['haha'].values[i]):
        post_df_full_with_reactions['haha'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['wow'].values[i]):
        post_df_full_with_reactions['wow'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['sad'].values[i]):
        post_df_full_with_reactions['sad'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['angry'].values[i]):
        post_df_full_with_reactions['angry'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['care'].values[i]):
        post_df_full_with_reactions['care'].values[i] = 0

    if pd.isna(post_df_full_with_reactions['shares'].values[i]):
        post_df_full_with_reactions['shares'].values[i] = 0
    
    if pd.isna(post_df_full_with_reactions['comments'].values[i]):
        post_df_full_with_reactions['comments'].values[i] = 0

reactions_data = post_df_full_with_reactions[['post_text','post_id','like','love','haha','wow','sad','angry','care',
                                 'shares','comments','reaction_count', 'time']]
reactions_data

,post_text,post_id,like,love,haha,wow,sad,angry,care,shares,comments,reaction_count,time
0,You can now redeem your My Nintendo Platinum P...,661994359446422,311.0,122.0,3.0,10.0,0.0,0.0,9.0,64,24,455,2023-11-28 08:30:00
1,The Tetris 99 38th MAXIMUS CUP event will run ...,661989386113586,62.0,11.0,0.0,0.0,0.0,0.0,1.0,17,5,74,2023-11-28 08:15:00
2,The Tetris 99 37th MAXIMUS CUP event will run ...,661985226114002,42.0,11.0,0.0,0.0,0.0,1.0,0.0,16,3,54,2023-11-28 08:01:10
3,Groups ranging in size from 2 to 100 people ca...,660425176270007,144.0,21.0,4.0,3.0,0.0,1.0,4.0,18,28,177,2023-11-25 03:00:38
4,When’s the last time you visited Paldea? There...,660388266273698,316.0,96.0,27.0,3.0,1.0,2.0,6.0,28,60,451,2023-11-25 01:00:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,"Mario, Mallow, and… Bowser? Join this team of ...",647189700926888,1865.0,755.0,3.0,18.0,0.0,0.0,35.0,177,217,2676,2023-10-31 01:00:00
89,The first F-ZERO game has returned as a 99-pla...,647166684262523,356.0,90.0,0.0,5.0,0.0,2.0,5.0,38,21,458,2023-10-31 00:00:23
90,Expect the unexpected in Super Mario Bros. Won...,645738844405307,519.0,151.0,0.0,2.0,1.0,0.0,9.0,53,59,682,2023-10-28 06:00:18
91,To celebrate the two-year anniversary of the P...,645647254414466,176.0,35.0,2.0,4.0,0.0,0.0,1.0,16,5,218,2023-10-28 02:00:01
92,Splatoween is almost here! Will you shuffle wi...,645482841097574,494.0,273.0,2.0,5.0,0.0,0.0,10.0,126,28,784,2023-10-27 20:00:03

Chuyển thời gian time thành thứ, ngày và giờ

In [35]:
reactions_data['time'] = pd.to_datetime(time_data['time'], format='ISO8601')
reactions_data['Day'] = reactions_data['time'].dt.day_name()
reactions_data['date'] = reactions_data['time'].dt.date
reactions_data['hour'] = reactions_data['time'].dt.hour
reactions_data

,post_text,post_id,like,love,haha,wow,sad,angry,care,shares,comments,reaction_count,Day,date,hour,time
0,You can now redeem your My Nintendo Platinum P...,661994359446422,311.0,122.0,3.0,10.0,0.0,0.0,9.0,64,24,455,Tuesday,2023-11-28,8,2023-11-28 08:30:00
1,The Tetris 99 38th MAXIMUS CUP event will run ...,661989386113586,62.0,11.0,0.0,0.0,0.0,0.0,1.0,17,5,74,Tuesday,2023-11-28,8,2023-11-28 08:15:00
2,The Tetris 99 37th MAXIMUS CUP event will run ...,661985226114002,42.0,11.0,0.0,0.0,0.0,1.0,0.0,16,3,54,Tuesday,2023-11-28,8,2023-11-28 08:01:10
3,Groups ranging in size from 2 to 100 people ca...,660425176270007,144.0,21.0,4.0,3.0,0.0,1.0,4.0,18,28,177,Saturday,2023-11-25,3,2023-11-25 03:00:38
4,When’s the last time you visited Paldea? There...,660388266273698,316.0,96.0,27.0,3.0,1.0,2.0,6.0,28,60,451,Saturday,2023-11-25,1,2023-11-25 01:00:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,"Mario, Mallow, and… Bowser? Join this team of ...",647189700926888,1865.0,755.0,3.0,18.0,0.0,0.0,35.0,177,217,2676,Tuesday,2023-10-31,1,2023-10-31 01:00:00
89,The first F-ZERO game has returned as a 99-pla...,647166684262523,356.0,90.0,0.0,5.0,0.0,2.0,5.0,38,21,458,Tuesday,2023-10-31,0,2023-10-31 00:00:23
90,Expect the unexpected in Super Mario Bros. Won...,645738844405307,519.0,151.0,0.0,2.0,1.0,0.0,9.0,53,59,682,Saturday,2023-10-28,6,2023-10-28 06:00:18
91,To celebrate the two-year anniversary of the P...,645647254414466,176.0,35.0,2.0,4.0,0.0,0.0,1.0,16,5,218,Saturday,2023-10-28,2,2023-10-28 02:00:01
92,Splatoween is almost here! Will you shuffle wi...,645482841097574,494.0,273.0,2.0,5.0,0.0,0.0,10.0,126,28,784,Friday,2023-10-27,20,2023-10-27 20:00:03

In [36]:
reactions_data.to_csv('reactions_data.csv')